name: project_1
description: A default Flutter project template.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  connectivity_plus: ^6.0.3
  #  date_range_form_field: ^1.0.2
  device_info_plus: ^10.1.0
  drift: ^2.13.0
  easy_localization: ^3.0.7
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_plugin_android_lifecycle: ^2.0.1
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.0.7
  freezed: ^2.0.3+1
  geolocator:
  geocoding:
  #  fullscreen: ^1.0.3
  html: ^0.15.0
  http: ^1.1.0
  image: ^4.1.3
  image_cropper: ^7.0.5
  image_editor: ^1.3.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  firebase_core: ^3.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  cloud_firestore: ^5.0.1
  #  firebase_auth: ^3.1.1
  path: ^1.8.2
  path_provider: ^2.1.0
  sqflite: any
  sqflite_migration: ^0.3.0
  provider: ^6.0.1
  json_annotation: ^4.3.0
  #  nfc_manager: ^3.2.0
  package_info_plus: ^8.0.0
  pdf: any
  permission_handler: ^11.0.1
  shared_preferences: ^2.0.6
  sms_autofill: ^2.3.0
  store_redirect: ^2.0.1
  url_launcher: ^6.0.9

  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.0.0
#  lint: ^1.7.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #    - assets/translations/
  #    - assets/flags/
  #    - images/

  #   - images/a_dot_burr.jpeg

#  fonts:
#    - family: Anton
#      fonts:
#        - asset: fonts/Anton-Regular.ttf
#          style: italic
